/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.mergeOpenApi

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'com.github.mergeOpenApi.greeting' plugin.
 */
class MergeOpenapiPluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('com.github.merge-openApi')
            }
            
            mergeOpenapi {
              input = [file("./build.gradle.kts")]
            }
            
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("mergeOpenapi")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        // Verify the result
        assertTrue(result.output.contains("Hello from plugin 'com.github.mergeOpenApi.greeting'"))
    }
}
